version: '3.8'

services:

  example-frontend:
    build: ../../../material-applications/example-frontend/.
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - example-backend

  example-backend:
    build: ../../../material-applications/example-backend/.
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=example-db
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - redis
      - example-db

  redis:
    image: redis:alpine
    restart: unless-stopped

  example-db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: example-db