version: '3.8'

services:

  example-frontend:
    build: ../../../material-applications/example-frontend/.
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - example-backend

  example-backend:
    build: ../../../material-applications/example-backend/.
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped
